# 1.1 - Numpy  (Numerical Python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


![numpy](images/numpy.png)

NumPy es el paquete fundamental para computación cientifíca en python. Es una librería de python nos permite manejar vectores, matrices, [tensores](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) (arrays multidimensionales) y además realizar todas las operaciones matemáticas y lógicas de los mismos, como la manipulación de la dimensión, ordenado, selección, I/O, operaciones estadísticas, transformadas de Fourier, simulación aleatoria y un largo etcétera. Constituye la herramienta de álgebra lineal.

## Recordatorio de álgebra

+ Contenidos:

    + Concepto de tensor
    + Operaciones con vectores
        + Concepto de espacio vectorial y base
        + Suma de vectores
        + Producto escalar
        + Producto vectorial
    + Operaciones con matrices
        + Suma de matrices
        + Producto matricial
        + Matriz Identidad
        + Matriz Traspuesta (Hermítica)
        + Matriz Inversa 
        + Determinate

### Tensor

La palabra ['tensor'](https://es.wikipedia.org/wiki/C%C3%A1lculo_tensorial) se utiliza a menudo como abreviatura de campo tensorial, que es un valor tensorial definido en cada punto en una variedad. El primero en utilizar esta palabra fue William Rowan Hamilton en 1846, empleándola para lo que actualmente se conoce como módulo y fue Woldemar Voigt en 1899 quien la empleó en su acepción actual. La palabra tensor proviene del latín tensus, participio pasado de tendere 'estirar, extender'. El nombre se extendió porque la teoría de la elasticidad fue una de las primeras aplicaciones físicas donde se usaron tensores. Gregorio Ricci-Curbastro en 1890 desarrolló la notación actual con el nombre de geometría diferencial absoluta, y se popularizó con la publicación de Cálculo Diferencial Absoluto de Tullio Levi-Civita en 1900. Con la introducción de la teoría de la relatividad general por parte de Albert Einstein alrededor de 1915 se encontró su aplicación más pragmática. La Relatividad General es netamente tensorial. Einstein había aprendido del mismo Levi-Civita el uso de tensores con gran dificultad.

Podemos pensar en un tensor como la generalización del ente algebraico. Con un ejemplo se verá más claro.

Un **número**, cualquier número, $2$, $3.6$, $\pi$, $\phi$, $\sqrt{2}$, es un **tensor de rango $0$**.

Un **vector**, cualquier vector, sea como sea su longitud, $(1, 2, 3)$, $(0, 5, 2, 1, 5)$, $(9,2)$, es un **tensor de rango $1$**.

Una **matriz**, cualquier matriz, sean cuales sean sus dimensiones, es un **tensor de rango $2$**.

Un **cubo de Rubik** por ejemplo es un **tensor de rango $3$**.

Pensar en dimensiones superiores es complicado por no decir imposible, pero se pueden interpretar a través del contenido. Una **bolsa llena de cubos de Rubik** es un **tensor de rango $4$**.

Una **caja llena de bolsas que están llenas de cubos de Rubik es un tensor de rango $5$**.

Y así sucesivamente.

### Operaciones con vectores

**Espacio vectorial**

La definición matemática de [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) implica los conceptos de conjunto, ley de composición(operación) interna y ley de composición externa, definida sobre un segundo conjunto. Resumiendo, un espacio vectorial es una estructura creada sobre un conjunto no vacío con ambas leyes de composición. A los elementos de un espacio vectorial se les llama vectores.

Veamos un ejemplo:

Un espacio vectorial es el espacio tridimensional ${\Bbb R}^{3}$. Los elementos de ${\Bbb R}^{3}$ son vectores, por lo que la ley de composición interna es la suma de vectores. Para la ley de composición externa se necesita otro conjunto, que en esta caso son los números reales ${\Bbb R}$, y queda definida como el producto por escalares, multiplicar un vector por un número.



**Base vectorial**

Una [base](https://es.wikipedia.org/wiki/Base_(%C3%A1lgebra)) es un conjunto de vectores {$v_{1}, v_{2}, v_{3}, ... ,v_{n}$} que cumplen las siguientes propiedades:

+ Todos los elementos de la base pertenecen al mismo espacio vectorial.
+ Los elementos de la base forman un sistema linealmente independiente (ninguno es combinación lineal de los demás).
+ Cualquier elemento del espacio vectorial se puede escribir como combinación lineal de los elementos de la base (es lo que se llama sistema generador del espacio vectorial).

Ejemplo:

En ${\Bbb R}^{3}$, la base principal (llamada canónica) es {$(1,0,0), (0,1,0), (0,0,1)$}. Todos esos vectores pertenecen a ${\Bbb R}^{3}$, son linealmente independientes(ninguno puede ser una suma de los otros) y cualquier otro vector en ${\Bbb R}^{3}$ se puede representar como una suma de esos tres, una combinación lineal. No es única, otra base de ${\Bbb R}^{3}$ podría ser {$(1,1,1), (1,1,0), (1,0,0)$}



**Suma de vectores**

Los vectores se suman por componentes, lo que implica que ambos tienen la misma longitud. Por ejemplo en ${\Bbb R}^{3}$:

$$\vec{A}=A_{x}\vec{i}+A_{y}\vec{j}+A_{z}\vec{k}$$

$$\vec{B}=B_{x}\vec{i}+B_{y}\vec{j}+B_{z}\vec{k}$$

$$\vec{A}+\vec{B}=(B_{x}+A_{x})\vec{i}+(B_{y}+A_{y})\vec{j}+(B_{z}+A_{z})\vec{k}$$

$$$$

$$\vec{A}=(1,8,9)$$

$$\vec{B}=(4,3,0)$$

$$\vec{A}+\vec{B}=(5,11,9)$$



**Producto escalar**

Hay que diferenciar entre producto por escalares, un número por un vector resultando un vector, y el productor escalar donde se multiplican dos vectores resultando un número, un escalar.

+ Producto por escalares:

Se realiza elemento a elemento la multiplicación por el número:

$$\vec{A}=(1,8,9)$$

$$2*\vec{A}=(2,16,18)$$

+ Productos escalar:

Se realiza multiplicando elemento un vector fila por un vector columna y sumando los resultados. Hay que tener en cuenta, igual que en la suma, que ambos vectores tienen el mismo número de elementos. También se le llama producto punto (dot product) o producto interno (inner product).

$$\vec{A}\cdot\vec{B}=(1, 8, 9)\cdot\begin{pmatrix}4\\3\\0\end{pmatrix} = 1·4+8·3+9·0 = 4+24+0 = 28$$



**Producto vectorial**

En este caso, se multiplican dos vectores resultando otro vector. La manera más fácil de hacerlo es a través de un determinante:


$$\vec{A}\times \vec{B} = \begin{vmatrix}
\hat{\imath}&\hat{\jmath}&\hat{k}\\
1 & 8 & 9 \\
4 & 3 & 0
\end{vmatrix} = \begin{vmatrix}
8 & 9 \\
3 & 0
\end{vmatrix}·\hat{\imath} - 
\begin{vmatrix}
1 & 9 \\
4 & 0
\end{vmatrix}·\hat{\jmath} +
\begin{vmatrix}
1 & 8 \\
4 & 3
\end{vmatrix}·\hat{k} = (8·0-9·3)·\hat{\imath}-(1·0-9·4)·\hat{\jmath}+(1·3-8·4)·\hat{k}$$

$$\vec{A}\times \vec{B} = (-27, 36, -29)$$

### Operaciones con matrices


**Suma de matrices**

Las matrices tienen definidas sus dimensiones sugún el número de filas($m$) y de columnas($n$), y se representan como $A_{mxn}$. Para sumar matrices las dimensiones tienen que ser las mismas, igual que ocurría con los vectores, y se realiza elemento a elemento (element wise):


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}+\begin{pmatrix}
0 & 0 & 3 \\
2 & 2 & 7 
\end{pmatrix}=\begin{pmatrix}
5 & 7 & 4 \\
6 & 2 & 9 
\end{pmatrix}$$



**Producto matricial**

Para multiplicar matrices tenemos que tener en cuenta las dimensiones, porque el producto matricial no es conmutativo e incluso a veces no se puede realizar. El número de columnas de la primera matriz tiene que ser igual que el número de filas de la segunda y el resultado tendrá el número de filas de la primera y el número de columnas de la segunda. Es decir:

$$A_{rxn}\cdot B_{nxq} = C_{rxq}$$


$$\begin{pmatrix}
5 & 7 & 1 \\
4 & 0 & 2 
\end{pmatrix}\cdot\begin{pmatrix}
0 & 0 \\
2 & 3 \\
2 & 7 
\end{pmatrix}=\begin{pmatrix}
5·0+7·2+1·2 & 5·0+7·3+1·7 \\
4·0+0·2+2·2 & 4·0+0·3+2·7
\end{pmatrix}=\begin{pmatrix}
18 & 28 \\
4 & 14
\end{pmatrix}$$



**Matriz Identidad**

Elemento neutro de la multiplicación, solo $1_s$ en la diagonal:

$$I = \begin{pmatrix}
1&0&\cdots&0&0\\
0&1&\cdots&0&0\\
\vdots&\vdots&\ddots&\vdots&\vdots\\
0&\cdots&\cdots&\cdots&0\\
0&0&\cdots&1&0\\
0&0&\cdots&0&1\\
\end{pmatrix}$$



**Matriz traspuesta  (hermítica)**

La traspuesta $A^{T}$ de una matriz $A$ puede ser obtenida reflejando los elementos a lo largo de su diagonal.

$$A=\begin{pmatrix}
5 & 7 & 9 \\
4 & 0 & 7 \\
1 & 2 & 2
\end{pmatrix}$$

$$A^{T}=\begin{pmatrix}
5 & 4 & 1 \\
7 & 0 & 2 \\
9 & 7 & 2
\end{pmatrix}$$


Se le dice hermítica si los elementos son números complejos, es la traspuesta conjugada (el conjugado de $x+iy$ es $x-iy$).


**Matriz Inversa**

¿Como se dividen las matrices? Se multiplica por la inversa. El cálculo de la matriz inversa es:

$$A= \begin{pmatrix}
       a_{11} & a_{12} \\ 
       a_{21} & a_{22}
    \end{pmatrix}$$
    
    
$$A^{-1}=\begin{pmatrix}
a_{11} & a_{12} \\ 
a_{21} & a_{22}
\end{pmatrix}^{-1}
=\frac{1}{\lvert A\rvert}
\begin{pmatrix}
a_{22} & -a_{12} \\ 
-a_{21} &  a_{11}
\end{pmatrix}$$


**Determinante**

$$A=\begin{pmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{pmatrix}$$
  

$$$$


$$det(A)=\begin{vmatrix}
    1 & 3 & 2 & -6 \\ 
    0 & -1 & -4 & 1 \\ 
    0 & -2 & -6 & 3 \\ 
    0 & -2 & -10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 0 & 0 \\ 
    -2 & 1 & 0 \\ 
    -2 & 0 & 1
  \end{vmatrix}\cdot
  \begin{vmatrix}
    1 & 4 & 1 \\ 
    2 & 6 & 3 \\ 
    2 & 10 & 3
  \end{vmatrix}=\begin{vmatrix}
    1 & 4 & 1 \\ 
    0 & -2 & 1 \\ 
    0 & 2 & 1
  \end{vmatrix}
  =
  \begin{vmatrix}
    -2 & 1 \\ 
    2 & 1
  \end{vmatrix}
  =-4$$
  
  

**Veamos algo de todo esto en python:**


**Arrays**

In [ ]:
%pip install numpy

In [1]:
import numpy as np

In [2]:
# vector, tensor rango 1

vector=np.random.random(5)  # numeros aleatorios uniformemente distribuidos entre 0 y 1

vector

array([0.12379802, 0.15793587, 0.32928778, 0.50972373, 0.10333237])

In [3]:
# matriz, tensor rango 2

matriz=np.random.random((10, 4))

matriz

array([[0.73025847, 0.55959487, 0.96328389, 0.56720502],
       [0.27997071, 0.44042769, 0.74858191, 0.31645738],
       [0.15433858, 0.33986716, 0.06245982, 0.61414436],
       [0.45849808, 0.1136465 , 0.69257703, 0.5785437 ],
       [0.58654287, 0.7827043 , 0.67680145, 0.09221364],
       [0.41698332, 0.57962386, 0.49734446, 0.41421755],
       [0.79561229, 0.55664239, 0.57768905, 0.47730728],
       [0.75622748, 0.67717355, 0.67114068, 0.71687293],
       [0.60862812, 0.26156679, 0.20460951, 0.77461889],
       [0.43066963, 0.47376122, 0.89259497, 0.90494275]])

In [4]:
type(matriz)

numpy.ndarray

In [5]:
# dimension

matriz.shape

(10, 4)

In [6]:
# nº de elementos

matriz.size

40

In [7]:
matriz[0]   # primera fila de la matriz

array([0.73025847, 0.55959487, 0.96328389, 0.56720502])

In [8]:
matriz[0][-1]

0.5672050177818657

In [9]:
# cubo, tensor de rango 3

cubo=np.random.random((3, 3, 2))

cubo

array([[[0.09975886, 0.70200917],
        [0.95761337, 0.14058284],
        [0.72878267, 0.80686697]],

       [[0.0546299 , 0.17913511],
        [0.58327371, 0.94139973],
        [0.36267934, 0.15914117]],

       [[0.10576604, 0.58701197],
        [0.11994663, 0.20564252],
        [0.45182838, 0.72536356]]])

In [10]:
# tensor de rango 4

tensor=np.random.random((2, 3, 4, 5))

tensor

array([[[[0.55188617, 0.09433146, 0.51008748, 0.74650698, 0.95724027],
         [0.64499527, 0.44841569, 0.88679015, 0.37409472, 0.24754355],
         [0.05708293, 0.47251935, 0.72854844, 0.260231  , 0.49431863],
         [0.5981143 , 0.94977909, 0.67799066, 0.2846646 , 0.40197757]],

        [[0.57470495, 0.01090533, 0.86385709, 0.79575212, 0.7534077 ],
         [0.39472781, 0.4077514 , 0.62593237, 0.29222811, 0.56983032],
         [0.93675567, 0.43235746, 0.82851489, 0.98307553, 0.86481922],
         [0.99238566, 0.17342199, 0.68471887, 0.57292999, 0.71087026]],

        [[0.06521877, 0.14789081, 0.55549244, 0.46654715, 0.80720157],
         [0.24818477, 0.60733638, 0.08407895, 0.17038667, 0.36997871],
         [0.73846608, 0.84005675, 0.63565651, 0.99775709, 0.77081735],
         [0.17419656, 0.62026685, 0.47237529, 0.89820326, 0.94976422]]],


       [[[0.09129362, 0.61559694, 0.18451873, 0.43556664, 0.91983241],
         [0.74524822, 0.33817347, 0.89987746, 0.23714874, 0.88083342]

In [11]:
type(tensor)

numpy.ndarray

In [12]:
tensor[0]

array([[[0.55188617, 0.09433146, 0.51008748, 0.74650698, 0.95724027],
        [0.64499527, 0.44841569, 0.88679015, 0.37409472, 0.24754355],
        [0.05708293, 0.47251935, 0.72854844, 0.260231  , 0.49431863],
        [0.5981143 , 0.94977909, 0.67799066, 0.2846646 , 0.40197757]],

       [[0.57470495, 0.01090533, 0.86385709, 0.79575212, 0.7534077 ],
        [0.39472781, 0.4077514 , 0.62593237, 0.29222811, 0.56983032],
        [0.93675567, 0.43235746, 0.82851489, 0.98307553, 0.86481922],
        [0.99238566, 0.17342199, 0.68471887, 0.57292999, 0.71087026]],

       [[0.06521877, 0.14789081, 0.55549244, 0.46654715, 0.80720157],
        [0.24818477, 0.60733638, 0.08407895, 0.17038667, 0.36997871],
        [0.73846608, 0.84005675, 0.63565651, 0.99775709, 0.77081735],
        [0.17419656, 0.62026685, 0.47237529, 0.89820326, 0.94976422]]])

In [13]:
tensor[0:1]

array([[[[0.55188617, 0.09433146, 0.51008748, 0.74650698, 0.95724027],
         [0.64499527, 0.44841569, 0.88679015, 0.37409472, 0.24754355],
         [0.05708293, 0.47251935, 0.72854844, 0.260231  , 0.49431863],
         [0.5981143 , 0.94977909, 0.67799066, 0.2846646 , 0.40197757]],

        [[0.57470495, 0.01090533, 0.86385709, 0.79575212, 0.7534077 ],
         [0.39472781, 0.4077514 , 0.62593237, 0.29222811, 0.56983032],
         [0.93675567, 0.43235746, 0.82851489, 0.98307553, 0.86481922],
         [0.99238566, 0.17342199, 0.68471887, 0.57292999, 0.71087026]],

        [[0.06521877, 0.14789081, 0.55549244, 0.46654715, 0.80720157],
         [0.24818477, 0.60733638, 0.08407895, 0.17038667, 0.36997871],
         [0.73846608, 0.84005675, 0.63565651, 0.99775709, 0.77081735],
         [0.17419656, 0.62026685, 0.47237529, 0.89820326, 0.94976422]]]])

In [14]:
tensor[1, 2]  # del segundo cubo, dame la tercera capa

array([[0.46001775, 0.15198249, 0.25757201, 0.26499724, 0.80045304],
       [0.3696715 , 0.15193968, 0.0706385 , 0.78255438, 0.07878829],
       [0.01033714, 0.13231708, 0.25023454, 0.29333544, 0.50496645],
       [0.4782621 , 0.09470452, 0.0531766 , 0.19686295, 0.58753552]])

In [15]:
tensor[1, 2, 3, 4]  # del segundo cubo, la tercera capa, cuarta fila dame el quinto elemento

0.5875355233673376

In [16]:
tensor[1][2][3][4]

0.5875355233673376

In [19]:
# de listas a arrays

lst=[7, 8, 9]

array=np.array(lst)

array.shape

(3,)

In [20]:
lst.shape

AttributeError: 'list' object has no attribute 'shape'

In [21]:
lst_lst=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array=np.array(lst_lst)

array.shape

(3, 3)

In [22]:
type(array)

numpy.ndarray

In [23]:
for e in array:
    print(e)

[1 2 3]
[4 5 6]
[7 8 9]


**Operaciones matemáticas**

In [24]:
matriz

array([[0.73025847, 0.55959487, 0.96328389, 0.56720502],
       [0.27997071, 0.44042769, 0.74858191, 0.31645738],
       [0.15433858, 0.33986716, 0.06245982, 0.61414436],
       [0.45849808, 0.1136465 , 0.69257703, 0.5785437 ],
       [0.58654287, 0.7827043 , 0.67680145, 0.09221364],
       [0.41698332, 0.57962386, 0.49734446, 0.41421755],
       [0.79561229, 0.55664239, 0.57768905, 0.47730728],
       [0.75622748, 0.67717355, 0.67114068, 0.71687293],
       [0.60862812, 0.26156679, 0.20460951, 0.77461889],
       [0.43066963, 0.47376122, 0.89259497, 0.90494275]])

In [25]:
matriz.sum()   # suma de todos los elementos

21.446344148260522

In [26]:
np.sum(matriz)

21.446344148260522

In [27]:
matriz.sum(axis=0)   # suma por columnas

array([5.21772955, 4.78500833, 5.98708277, 5.4565235 ])

In [28]:
matriz.sum(axis=1)   # suma por filas

array([2.82034225, 1.78543769, 1.17080992, 1.84326531, 2.13826225,
       1.9081692 , 2.40725101, 2.82141464, 1.8494233 , 2.70196858])

In [29]:
np.sum(matriz, axis=1)

array([2.82034225, 1.78543769, 1.17080992, 1.84326531, 2.13826225,
       1.9081692 , 2.40725101, 2.82141464, 1.8494233 , 2.70196858])

In [30]:
np.sum(matriz, axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [31]:
np.sum(cubo, axis=2)

array([[0.80176803, 1.09819621, 1.53564965],
       [0.23376501, 1.52467344, 0.52182051],
       [0.69277801, 0.32558915, 1.17719194]])

In [32]:
tensor.shape

(2, 3, 4, 5)

In [33]:
tensor.sum(axis=0).shape     # suma por cubos

(3, 4, 5)

In [34]:
tensor.sum(axis=1).shape     # suma por capas del cubo

(2, 4, 5)

In [35]:
tensor.sum(axis=2).shape     # suma por filas

(2, 3, 5)

In [36]:
tensor.sum(axis=3).shape     # suma por columnas

(2, 3, 4)

In [37]:
matriz.min()  # minimo de toda la matriz

0.06245981844575976

In [38]:
matriz.max()  # maximo de toda la matriz

0.9632838860329216

In [39]:
matriz.max(axis=0)  # maximo de cada columna

array([0.79561229, 0.7827043 , 0.96328389, 0.90494275])

In [43]:
matriz[0:2, 0:2].max()

0.7302584744140941

In [44]:
matriz.mean()   # media de toda la matriz

0.536158603706513

In [45]:
matriz.mean(axis=0)   # media por columna

array([0.52177295, 0.47850083, 0.59870828, 0.54565235])

In [46]:
matriz.mean(axis=1)   # media por fila

array([0.70508556, 0.44635942, 0.29270248, 0.46081633, 0.53456556,
       0.4770423 , 0.60181275, 0.70535366, 0.46235583, 0.67549214])

In [48]:
matriz.std()   # desviacion standard la matriz

0.22614707130587255

In [49]:
matriz.var()    # varianza 

0.0511424978602234

In [50]:
matriz.var(axis=0)

array([0.04019228, 0.03557892, 0.07154959, 0.04971524])

In [51]:
matriz.var() ** 0.5

0.22614707130587255

In [52]:
matriz[0]

array([0.73025847, 0.55959487, 0.96328389, 0.56720502])

In [55]:
-matriz[1]

array([-0.27997071, -0.44042769, -0.74858191, -0.31645738])

In [54]:
np.add(matriz[0], matriz[1])   # suma de vectores elemento a elemento

array([1.01022919, 1.00002256, 1.7118658 , 0.88366239])

In [56]:
np.add(matriz[0], -matriz[1]) 

array([0.45028776, 0.11916718, 0.21470197, 0.25074764])

In [57]:
np.subtract(matriz[0], matriz[1]) 

array([0.45028776, 0.11916718, 0.21470197, 0.25074764])

In [59]:
np.prod(matriz)     # productorio, multiplica todos entre si

4.890460522457076e-14

In [60]:
1e3   # notacion cientifica

1000.0

In [61]:
1e-3

0.001

In [62]:
np.multiply(matriz[0], matriz[1])   # multiplica elemento a elemento

array([0.20445099, 0.24646108, 0.72109689, 0.17949621])

In [66]:
np.dot(matriz[1], matriz[0])  # producto escalar de vectores, (dot product, inner product)

1.3515051670539275

In [68]:
np.cross(matriz[1][:3], matriz[0][:3])  # producto vectorial, maximo 3 dim

array([ 0.0053543 ,  0.27696701, -0.16495588])

In [69]:
matriz.transpose()  # matriz traspuesta

array([[0.73025847, 0.27997071, 0.15433858, 0.45849808, 0.58654287,
        0.41698332, 0.79561229, 0.75622748, 0.60862812, 0.43066963],
       [0.55959487, 0.44042769, 0.33986716, 0.1136465 , 0.7827043 ,
        0.57962386, 0.55664239, 0.67717355, 0.26156679, 0.47376122],
       [0.96328389, 0.74858191, 0.06245982, 0.69257703, 0.67680145,
        0.49734446, 0.57768905, 0.67114068, 0.20460951, 0.89259497],
       [0.56720502, 0.31645738, 0.61414436, 0.5785437 , 0.09221364,
        0.41421755, 0.47730728, 0.71687293, 0.77461889, 0.90494275]])

In [70]:
matriz.T

array([[0.73025847, 0.27997071, 0.15433858, 0.45849808, 0.58654287,
        0.41698332, 0.79561229, 0.75622748, 0.60862812, 0.43066963],
       [0.55959487, 0.44042769, 0.33986716, 0.1136465 , 0.7827043 ,
        0.57962386, 0.55664239, 0.67717355, 0.26156679, 0.47376122],
       [0.96328389, 0.74858191, 0.06245982, 0.69257703, 0.67680145,
        0.49734446, 0.57768905, 0.67114068, 0.20460951, 0.89259497],
       [0.56720502, 0.31645738, 0.61414436, 0.5785437 , 0.09221364,
        0.41421755, 0.47730728, 0.71687293, 0.77461889, 0.90494275]])

In [72]:
np.matmul(matriz, matriz.T)     # multiplicacion de matrices

array([[2.09606123, 1.35150517, 0.71140728, 1.39371929, 1.57058118,
        1.34289032, 1.71970648, 1.98429729, 1.22729203, 1.95272492],
       [1.35150517, 0.9328803 , 0.434004  , 0.87995416, 1.04476248,
        0.87541079, 1.05140385, 1.23923103, 0.68390014, 1.28378871],
       [0.71140728, 0.434004  , 0.52040461, 0.50795624, 0.45544706,
        0.54680515, 0.64119607, 0.82904692, 0.67134046, 0.83900163],
       [1.39371929, 0.87995416, 0.50795624, 1.03751177, 0.87996714,
        0.84115058, 1.10428445, 1.30324619, 0.8986397 , 1.39304221],
       [1.57058118, 1.04476248, 0.45544706, 0.87996714, 1.42322211,
        1.07305264, 1.33734213, 1.49392093, 0.77162637, 1.31097878],
       [1.34289032, 0.87541079, 0.54680515, 0.84115058, 1.07305264,
        0.92876661, 1.13941977, 1.33856964, 0.82802027, 1.2729557 ],
       [1.71970648, 1.05140385, 0.64119607, 1.10428445, 1.33734213,
        1.13941977, 1.50439654, 1.70848667, 1.11776308, 1.55393974],
       [1.98429729, 1.23923103, 0.8290469

In [75]:
np.dot(matriz, matriz.T) 

array([[2.09606123, 1.35150517, 0.71140728, 1.39371929, 1.57058118,
        1.34289032, 1.71970648, 1.98429729, 1.22729203, 1.95272492],
       [1.35150517, 0.9328803 , 0.434004  , 0.87995416, 1.04476248,
        0.87541079, 1.05140385, 1.23923103, 0.68390014, 1.28378871],
       [0.71140728, 0.434004  , 0.52040461, 0.50795624, 0.45544706,
        0.54680515, 0.64119607, 0.82904692, 0.67134046, 0.83900163],
       [1.39371929, 0.87995416, 0.50795624, 1.03751177, 0.87996714,
        0.84115058, 1.10428445, 1.30324619, 0.8986397 , 1.39304221],
       [1.57058118, 1.04476248, 0.45544706, 0.87996714, 1.42322211,
        1.07305264, 1.33734213, 1.49392093, 0.77162637, 1.31097878],
       [1.34289032, 0.87541079, 0.54680515, 0.84115058, 1.07305264,
        0.92876661, 1.13941977, 1.33856964, 0.82802027, 1.2729557 ],
       [1.71970648, 1.05140385, 0.64119607, 1.10428445, 1.33734213,
        1.13941977, 1.50439654, 1.70848667, 1.11776308, 1.55393974],
       [1.98429729, 1.23923103, 0.8290469

In [76]:
np.tensordot(matriz, matriz)   # producto tensorial

array(13.54434185)

In [77]:
matriz.cumsum()   # sumatorio, suma acumulada

array([ 0.73025847,  1.28985334,  2.25313723,  2.82034225,  3.10031296,
        3.54074065,  4.28932256,  4.60577994,  4.76011852,  5.09998568,
        5.1624455 ,  5.77658986,  6.23508794,  6.34873444,  7.04131147,
        7.61985517,  8.20639804,  8.98910234,  9.66590379,  9.75811743,
       10.17510074, 10.75472461, 11.25206907, 11.66628662, 12.46189891,
       13.0185413 , 13.59623035, 14.07353763, 14.82976512, 15.50693866,
       16.17807934, 16.89495227, 17.50358039, 17.76514718, 17.96975668,
       18.74437557, 19.1750452 , 19.64880642, 20.54140139, 21.44634415])

In [78]:
matriz.sum()

21.446344148260522

In [79]:
matriz.cumprod()   # productorio, producto acumulada

array([7.30258474e-01, 4.08648895e-01, 3.93644895e-01, 2.23277360e-01,
       6.25111217e-02, 2.75316290e-02, 2.06096795e-02, 6.52208510e-03,
       1.00660932e-03, 3.42113456e-04, 2.13683443e-05, 1.31232483e-05,
       6.01698414e-06, 6.83809173e-07, 4.73590528e-07, 2.73992816e-07,
       1.60708533e-07, 1.25787259e-07, 8.51329993e-08, 7.85042362e-09,
       3.27349567e-09, 1.89739621e-09, 9.43659499e-10, 3.90880330e-10,
       3.10989193e-10, 1.73109768e-10, 1.00003617e-10, 4.77324548e-11,
       3.60965942e-11, 2.44436588e-11, 1.64051337e-11, 1.17603962e-11,
       7.15770784e-12, 1.87221865e-12, 3.83073736e-13, 2.96736150e-13,
       1.27795248e-13, 6.05444326e-14, 5.40416562e-14, 4.89046052e-14])

In [80]:
np.inf

inf

In [81]:
type(np.inf)

float

In [82]:
np.nan

nan

In [83]:
type(np.nan)

float

In [86]:
type(matriz.tolist())

list

In [87]:
np.linalg.det(matriz[:4, :])   # determinante, tiene que ser matriz cuadrada

-0.05954431524060096

In [88]:
matriz[:4, :]

array([[0.73025847, 0.55959487, 0.96328389, 0.56720502],
       [0.27997071, 0.44042769, 0.74858191, 0.31645738],
       [0.15433858, 0.33986716, 0.06245982, 0.61414436],
       [0.45849808, 0.1136465 , 0.69257703, 0.5785437 ]])

**Dimensiones**

In [89]:
matriz.shape

(10, 4)

In [93]:
matriz.reshape((5, 8))  # redimensionar, mismo nº de elementos

array([[0.73025847, 0.55959487, 0.96328389, 0.56720502, 0.27997071,
        0.44042769, 0.74858191, 0.31645738],
       [0.15433858, 0.33986716, 0.06245982, 0.61414436, 0.45849808,
        0.1136465 , 0.69257703, 0.5785437 ],
       [0.58654287, 0.7827043 , 0.67680145, 0.09221364, 0.41698332,
        0.57962386, 0.49734446, 0.41421755],
       [0.79561229, 0.55664239, 0.57768905, 0.47730728, 0.75622748,
        0.67717355, 0.67114068, 0.71687293],
       [0.60862812, 0.26156679, 0.20460951, 0.77461889, 0.43066963,
        0.47376122, 0.89259497, 0.90494275]])

In [92]:
matriz.flatten()   # aplnar la matriz

array([0.73025847, 0.55959487, 0.96328389, 0.56720502, 0.27997071,
       0.44042769, 0.74858191, 0.31645738, 0.15433858, 0.33986716,
       0.06245982, 0.61414436, 0.45849808, 0.1136465 , 0.69257703,
       0.5785437 , 0.58654287, 0.7827043 , 0.67680145, 0.09221364,
       0.41698332, 0.57962386, 0.49734446, 0.41421755, 0.79561229,
       0.55664239, 0.57768905, 0.47730728, 0.75622748, 0.67717355,
       0.67114068, 0.71687293, 0.60862812, 0.26156679, 0.20460951,
       0.77461889, 0.43066963, 0.47376122, 0.89259497, 0.90494275])

In [96]:
matriz[0]=matriz[1]

In [97]:
matriz

array([[0.27997071, 0.44042769, 0.74858191, 0.31645738],
       [0.27997071, 0.44042769, 0.74858191, 0.31645738],
       [0.15433858, 0.33986716, 0.06245982, 0.61414436],
       [0.45849808, 0.1136465 , 0.69257703, 0.5785437 ],
       [0.58654287, 0.7827043 , 0.67680145, 0.09221364],
       [0.41698332, 0.57962386, 0.49734446, 0.41421755],
       [0.79561229, 0.55664239, 0.57768905, 0.47730728],
       [0.75622748, 0.67717355, 0.67114068, 0.71687293],
       [0.60862812, 0.26156679, 0.20460951, 0.77461889],
       [0.43066963, 0.47376122, 0.89259497, 0.90494275]])

In [99]:
a=matriz[0]

type(a)

numpy.ndarray

In [103]:
matriz+np.array([1, 2, 3, 4])

array([[1.27997071, 2.44042769, 3.74858191, 4.31645738],
       [1.27997071, 2.44042769, 3.74858191, 4.31645738],
       [1.15433858, 2.33986716, 3.06245982, 4.61414436],
       [1.45849808, 2.1136465 , 3.69257703, 4.5785437 ],
       [1.58654287, 2.7827043 , 3.67680145, 4.09221364],
       [1.41698332, 2.57962386, 3.49734446, 4.41421755],
       [1.79561229, 2.55664239, 3.57768905, 4.47730728],
       [1.75622748, 2.67717355, 3.67114068, 4.71687293],
       [1.60862812, 2.26156679, 3.20460951, 4.77461889],
       [1.43066963, 2.47376122, 3.89259497, 4.90494275]])

In [104]:
# listas

lst=[1, 2, 3]

lst

[1, 2, 3]

In [105]:
lst.sum()

AttributeError: 'list' object has no attribute 'sum'

In [106]:
sum(lst)

6

In [107]:
np.sum(lst)

6

In [109]:
np.array(lst).sum()

6

In [110]:
lst=np.array(lst)

lst

array([1, 2, 3])

In [111]:
lst.min()

1